let profissional_t = [
  { concluida: 010,  categoria: 'Profissional em T',tarefa: 'Especialista em Carreira' },
  { concluida: 020,  categoria: 'Profissional em T',tarefa: 'Coach de Transição de Carreira' },
  { concluida: 030,  categoria: 'Profissional em T',tarefa: 'Leader' },
  { concluida: 040,  categoria: 'Profissional em T',tarefa: 'Analise de dados - PowerBI' },
  { concluida: 050,  categoria: 'Profissional em T',tarefa: 'Ciencia de dados' },
  { concluida: 060,  categoria: 'Profissional em T',tarefa: 'Devops' },
  { concluida: 070,  categoria: 'Profissional em T',tarefa: 'Machine Learning Enginer' },
  { concluida: 080,  categoria: 'Profissional em T',tarefa: 'Manager project' },
  { concluida: 090,  categoria: 'Profissional em T',tarefa: 'Manager project > Aprender https://www.youtube.com/watch?v=35X6v3aE86o' },
  { concluida: 100,  categoria: 'Profissional em T',tarefa: 'Manager project > Descrever projetos e suas integrações cronologicamente' },
  { concluida: 100,  categoria: 'Profissional em T',tarefa: 'Manager project > Profissões https://techguide.sh/' },  
  { concluida: 000,  categoria: 'Projetos',tarefa: 'Usar Git para integrar com um projeto scrum' },
  { concluida: 000,  categoria: 'Redes',tarefa: 'Quora' },
  { concluida: 100,  categoria: 'Redes',tarefa: 'LinkedIn' },
  { concluida: 100,  categoria: 'Redes',tarefa: 'GitHub' },
  { concluida: 000,  categoria: 'Redes',tarefa: 'Profissões: Engenheiro de Software' },
  { concluida: 000,  categoria: 'Redes',tarefa: 'Profissões: Gestor de Comunidade' },
  { concluida: 000,  categoria: 'Redes',tarefa: 'Profissões: Especialista em Networking' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Trello' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Jira' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Kanban' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Scrum' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Management 3.0' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'XP' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Miro' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'ClickUp' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Profissões: Gerente de Projetos' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Profissões: Scrum Master' },
  { concluida: 000,  categoria: 'Gestão Ágil',tarefa: 'Profissões: Product Owner' },
  { concluida: 000,  categoria: 'Comunicação',tarefa: 'Slack' },
  { concluida: 100,  categoria: 'Comunicação',tarefa: 'Microsoft Teams' },
  { concluida: 000,  categoria: 'Comunicação',tarefa: 'Profissões: Gerente de Projetos' },
  { concluida: 000,  categoria: 'Comunicação',tarefa: 'Profissões: Analista de Comunicação' },
  { concluida: 100,  categoria: 'Colaboração',tarefa: 'Google docs' },
  { concluida: 000,  categoria: 'Colaboração',tarefa: 'Dropbox paper' },
  { concluida: 000,  categoria: 'Colaboração',tarefa: 'Microsof office' },
  { concluida: 000,  categoria: 'Colaboração',tarefa: 'Profissões: Engenheiro de Software (trabalho em equipe)' },
  { concluida: 000,  categoria: 'Colaboração',tarefa: 'Profissões: Analista de Dados' },
  { concluida: 000,  categoria: 'Video conferencias',tarefa: 'zoom' },
  { concluida: 100,  categoria: 'Video conferencias',tarefa: 'google meet' },
  { concluida: 100,  categoria: 'Video conferencias',tarefa: 'microsoft teams' },
  { concluida: 000,  categoria: 'Video conferencias',tarefa: 'Profissões: Trabalhos Remotos em Geral' },
  { concluida: 000,  categoria: 'Video conferencias',tarefa: 'Profissões: Gerente de Projetos' },
  { concluida: 000,  categoria: 'Documentação',tarefa: 'confluence' },
  { concluida: 000,  categoria: 'Documentação',tarefa: 'sharepoint' },
  { concluida: 000,  categoria: 'Documentação',tarefa: 'Profissões: Engenheiro de Software' },
  { concluida: 000,  categoria: 'Documentação',tarefa: 'Profissões: Analista de Dados' },
  { concluida: 100,  categoria: 'Versionamento',tarefa: 'git' },
  { concluida: 000,  categoria: 'Versionamento',tarefa: 'Profissões: Engenheiro de Software' },
  { concluida: 000,  categoria: 'Versionamento',tarefa: 'Profissões: GitOps Engineer' },
  { concluida: 100,  categoria: 'Front End (UX)',tarefa: 'Figma' },
  { concluida: 000,  categoria: 'Front End (UX)',tarefa: 'Illustrator' },
  { concluida: 100,  categoria: 'Front End (UX)',tarefa: 'Photoshop' },
  { concluida: 000,  categoria: 'Front End (UX)',tarefa: 'Canvas' },
  { concluida: 000,  categoria: 'Front End (UX)',tarefa: 'Next.js' },
  { concluida: 000,  categoria: 'Matematica',tarefa: 'Grafos' },
  { concluida: 000,  categoria: 'Back End',tarefa: 'Node' },
  { concluida: 000,  categoria: 'Back End',tarefa: 'mongoDB' },
  { concluida: 100,  categoria: 'Mobile',tarefa: 'Dart' },
  { concluida: 100,  categoria: 'Mobile',tarefa: 'Fluter' },
  { concluida: 000,  categoria: 'Fullstack',tarefa: '???' },
  { concluida: 100,  categoria: 'IDEs',tarefa: 'vs-code (C# .Net + live-server browser-sync)' },
  { concluida: 000,  categoria: 'IDEs',tarefa: 'IntelliJ IDEA' },
  { concluida: 100,  categoria: 'IDEs',tarefa: 'Android Studio' },
  { concluida: 100,  categoria: 'IDEs',tarefa: 'Arduino IDE' },    
  { concluida: 050,  categoria: 'Plataforma',tarefa: 'Plataformas Backend como Serviço (BaaS) e Bancos de Dados > Firebase' },
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Plataformas Backend como Serviço (BaaS) e Bancos de Dados > https://console.neon.tech/'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Plataformas Backend como Serviço (BaaS) e Bancos de Dados > https://dashboard.render.com/ '},  
  { concluida: 050,  categoria: 'Plataforma',tarefa: 'Ambientes de Desenvolvimento e Execução de Código Online > PlayCode - https://PlayCode.io'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ambientes de Desenvolvimento e Execução de Código Online > RunJS.co - https://runjs.co'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ambientes de Desenvolvimento e Execução de Código Online > RunJs.app - https://runjs.app/play'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ambientes de Desenvolvimento e Execução de Código Online > JS Playground - https://www.jsplayground.dev'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas para Compartilhamento de Código e Textos > GitHub Gist - https://gist.github.com'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas para Compartilhamento de Código e Textos > PasteBin - https://pastebin.com'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas para Criação de Imagens de Código e Readmes > Carbon - https://carbon.now.sh'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas para Criação de Imagens de Código e Readmes > https://readme.so/pt/editor'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas para Geração de Projetos e Perfis > https://start.spring.io/'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas para Geração de Projetos e Perfis > https://profile-readme-generator.com/result'},
  { concluida: 000,  categoria: 'Plataforma',tarefa: 'Ferramentas de Desenvolvimento Android > https://github.com/sickcodes/dock-droid?tab=readme-ov-file'},  
  { concluida: 000,  categoria: 'Frameworks',tarefa: '.Net Core Bootstrap' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'reactily' },
  { concluida: 100,  categoria: 'Frameworks',tarefa: 'Node.js' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'kotlin' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'react nactive' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Django' },  
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'dino' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'ban' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'zig' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Rust' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'testes automatizados (integração continua)' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular https://techguide.sh/pt-BR/path/angular/' },
  { concluida: 100,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > HTML - Fundamentos' },
  { concluida: 100,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > CSS - Fundamentos' },
  { concluida: 100,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > JavaScript - Fundamentos' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > TypeScript - Fundamentos' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > Angular - Fundamentos' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > Conceitos de Orientação a Objetos' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 1 > RxJS - Fundamentos' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 2 > Angular - Templates' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 2 > Angular - Renderização' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 2 > Angular - Services' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 2 > Angular - Roteamento' },
  { concluida: 100,  categoria: 'Frameworks',tarefa: 'Angular > Nível 2 > Angular - CLI (Interface de Linha de Comando)' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Angular - Gerenciamento de Estado' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Angular - Formulários' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Angular - Módulos' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Angular - Injeção de Dependências' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Angular - Testes' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > GraphQL' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Apollo Client' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Angular > Nível 3 > Angular - Design System' },
  { concluida: 000,  categoria: 'Frameworks',tarefa: 'Vue' },
  { concluida: 000,  categoria: 'Games',tarefa: 'unreal (Linguagem base: C++)' },
  { concluida: 000,  categoria: 'Games',tarefa: 'cryengine (Linguagem base: C++)' },
  { concluida: 000,  categoria: 'Games',tarefa: 'unity (Linguagem base: C#)' },
  { concluida: 000,  categoria: 'Games',tarefa: 'godot (Linguagem base: GDScript C++)' },
  { concluida: 000,  categoria: 'Games',tarefa: 'construct 3 (Linguagem base: JavaScript)' },
  { concluida: 000,  categoria: 'Webservices',tarefa: 'https://dashboard.render.com/' },
  { concluida: 000,  categoria: 'Webservices',tarefa: 'https://console.neon.tech/' },  
  { concluida: 080,  categoria: 'Ingles avançado (Estou no B1 )',tarefa: 'A B C 1 e 2 -> duolingo' },
  { concluida: 100,  categoria: 'Ingles avançado (Estou no B1 )',tarefa: 'Bronze Prata Ouro Safira Rubi Esmeralda Ametista Pérola Obsidiana e Diamante.' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'linkedin' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'cod lab' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'cod.og' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'frecodcamp.org' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'exercism.io' },
  { concluida: 100,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > arrays' },
  { concluida: 100,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > listas encadeadas' },
  { concluida: 100,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > pilhas e filas' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > tabelas hash' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > dicionario de dados' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > arvores binarias' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados > heap' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Estrutura de dados' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Sorting > quick' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Sorting > merge' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Sorting > radix' },
  { concluida: 100,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Sorting' },
  { concluida: 100,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Busca binaria' },
  { concluida: 100,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'Recursão' },
  { concluida: 000,  categoria: 'Fazer testes de habilidades (Desfios/BootCamp)',tarefa: 'https://lp.cloudtreinamentos.com/intensivoes.' }
];